/*
* generated by Xtext
*/
package com.selenium.gram.xtext.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class SlnDslGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Model");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cSubsAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cSubsSubprocedureParserRuleCall_0_0 = (RuleCall)cSubsAssignment_0.eContents().get(0);
		private final Keyword cMainKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cMainAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cMainInstructionParserRuleCall_2_0 = (RuleCall)cMainAssignment_2.eContents().get(0);
		private final Keyword cEndmainKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		/// *
		// * Le modele
		// * / Model:
		//	subs+=Subprocedure* "main" main+=Instruction+ "endmain";
		public ParserRule getRule() { return rule; }

		//subs+=Subprocedure* "main" main+=Instruction+ "endmain"
		public Group getGroup() { return cGroup; }

		//subs+=Subprocedure*
		public Assignment getSubsAssignment_0() { return cSubsAssignment_0; }

		//Subprocedure
		public RuleCall getSubsSubprocedureParserRuleCall_0_0() { return cSubsSubprocedureParserRuleCall_0_0; }

		//"main"
		public Keyword getMainKeyword_1() { return cMainKeyword_1; }

		//main+=Instruction+
		public Assignment getMainAssignment_2() { return cMainAssignment_2; }

		//Instruction
		public RuleCall getMainInstructionParserRuleCall_2_0() { return cMainInstructionParserRuleCall_2_0; }

		//"endmain"
		public Keyword getEndmainKeyword_3() { return cEndmainKeyword_3; }
	}

	public class SubprocedureElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Subprocedure");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSubKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cHeadAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cHeadHeadParserRuleCall_1_0 = (RuleCall)cHeadAssignment_1.eContents().get(0);
		private final Assignment cBodyAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cBodyInstructionParserRuleCall_2_0 = (RuleCall)cBodyAssignment_2.eContents().get(0);
		private final Keyword cEndsubKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Subprocedure:
		//	"sub" head=Head body+=Instruction+ "endsub";
		public ParserRule getRule() { return rule; }

		//"sub" head=Head body+=Instruction+ "endsub"
		public Group getGroup() { return cGroup; }

		//"sub"
		public Keyword getSubKeyword_0() { return cSubKeyword_0; }

		//head=Head
		public Assignment getHeadAssignment_1() { return cHeadAssignment_1; }

		//Head
		public RuleCall getHeadHeadParserRuleCall_1_0() { return cHeadHeadParserRuleCall_1_0; }

		//body+=Instruction+
		public Assignment getBodyAssignment_2() { return cBodyAssignment_2; }

		//Instruction
		public RuleCall getBodyInstructionParserRuleCall_2_0() { return cBodyInstructionParserRuleCall_2_0; }

		//"endsub"
		public Keyword getEndsubKeyword_3() { return cEndsubKeyword_3; }
	}

	public class HeadElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Head");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Assignment cNameAssignment_0_0 = (Assignment)cGroup_0.eContents().get(0);
		private final RuleCall cNameFunctionNameParserRuleCall_0_0_0 = (RuleCall)cNameAssignment_0_0.eContents().get(0);
		private final Keyword cLeftParenthesisRightParenthesisKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Assignment cNameAssignment_1_0 = (Assignment)cGroup_1.eContents().get(0);
		private final RuleCall cNameFunctionNameParserRuleCall_1_0_0 = (RuleCall)cNameAssignment_1_0.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Keyword cVarKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		private final Assignment cArgsIDAssignment_1_3 = (Assignment)cGroup_1.eContents().get(3);
		private final RuleCall cArgsIDVariableNameParserRuleCall_1_3_0 = (RuleCall)cArgsIDAssignment_1_3.eContents().get(0);
		private final Group cGroup_1_4 = (Group)cGroup_1.eContents().get(4);
		private final Keyword cCommaKeyword_1_4_0 = (Keyword)cGroup_1_4.eContents().get(0);
		private final Keyword cVarKeyword_1_4_1 = (Keyword)cGroup_1_4.eContents().get(1);
		private final Assignment cArgsIDAssignment_1_4_2 = (Assignment)cGroup_1_4.eContents().get(2);
		private final RuleCall cArgsIDVariableNameParserRuleCall_1_4_2_0 = (RuleCall)cArgsIDAssignment_1_4_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_1_5 = (Keyword)cGroup_1.eContents().get(5);
		
		//Head:
		//	name=FunctionName "()" | name=FunctionName "(" "var" argsID+=VariableName ("," "var" argsID+=VariableName)* ")";
		public ParserRule getRule() { return rule; }

		//name=FunctionName "()" | name=FunctionName "(" "var" argsID+=VariableName ("," "var" argsID+=VariableName)* ")"
		public Alternatives getAlternatives() { return cAlternatives; }

		//name=FunctionName "()"
		public Group getGroup_0() { return cGroup_0; }

		//name=FunctionName
		public Assignment getNameAssignment_0_0() { return cNameAssignment_0_0; }

		//FunctionName
		public RuleCall getNameFunctionNameParserRuleCall_0_0_0() { return cNameFunctionNameParserRuleCall_0_0_0; }

		//"()"
		public Keyword getLeftParenthesisRightParenthesisKeyword_0_1() { return cLeftParenthesisRightParenthesisKeyword_0_1; }

		//name=FunctionName "(" "var" argsID+=VariableName ("," "var" argsID+=VariableName)* ")"
		public Group getGroup_1() { return cGroup_1; }

		//name=FunctionName
		public Assignment getNameAssignment_1_0() { return cNameAssignment_1_0; }

		//FunctionName
		public RuleCall getNameFunctionNameParserRuleCall_1_0_0() { return cNameFunctionNameParserRuleCall_1_0_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_1_1() { return cLeftParenthesisKeyword_1_1; }

		//"var"
		public Keyword getVarKeyword_1_2() { return cVarKeyword_1_2; }

		//argsID+=VariableName
		public Assignment getArgsIDAssignment_1_3() { return cArgsIDAssignment_1_3; }

		//VariableName
		public RuleCall getArgsIDVariableNameParserRuleCall_1_3_0() { return cArgsIDVariableNameParserRuleCall_1_3_0; }

		//("," "var" argsID+=VariableName)*
		public Group getGroup_1_4() { return cGroup_1_4; }

		//","
		public Keyword getCommaKeyword_1_4_0() { return cCommaKeyword_1_4_0; }

		//"var"
		public Keyword getVarKeyword_1_4_1() { return cVarKeyword_1_4_1; }

		//argsID+=VariableName
		public Assignment getArgsIDAssignment_1_4_2() { return cArgsIDAssignment_1_4_2; }

		//VariableName
		public RuleCall getArgsIDVariableNameParserRuleCall_1_4_2_0() { return cArgsIDVariableNameParserRuleCall_1_4_2_0; }

		//")"
		public Keyword getRightParenthesisKeyword_1_5() { return cRightParenthesisKeyword_1_5; }
	}

	public class FunctionReferenceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "FunctionReference");
		private final Assignment cFunctionNameAssignment = (Assignment)rule.eContents().get(1);
		private final CrossReference cFunctionNameFunctionNameCrossReference_0 = (CrossReference)cFunctionNameAssignment.eContents().get(0);
		private final RuleCall cFunctionNameFunctionNameIDTerminalRuleCall_0_1 = (RuleCall)cFunctionNameFunctionNameCrossReference_0.eContents().get(1);
		
		/// *
		// * Subprocedure
		// * / FunctionReference:
		//	functionName=[FunctionName];
		public ParserRule getRule() { return rule; }

		//functionName=[FunctionName]
		public Assignment getFunctionNameAssignment() { return cFunctionNameAssignment; }

		//[FunctionName]
		public CrossReference getFunctionNameFunctionNameCrossReference_0() { return cFunctionNameFunctionNameCrossReference_0; }

		//ID
		public RuleCall getFunctionNameFunctionNameIDTerminalRuleCall_0_1() { return cFunctionNameFunctionNameIDTerminalRuleCall_0_1; }
	}

	public class FunctionNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "FunctionName");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_0 = (RuleCall)cNameAssignment.eContents().get(0);
		
		//FunctionName:
		//	name=ID;
		public ParserRule getRule() { return rule; }

		//name=ID
		public Assignment getNameAssignment() { return cNameAssignment; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_0() { return cNameIDTerminalRuleCall_0; }
	}

	public class FunctionCallElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "FunctionCall");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final RuleCall cFunctionReferenceParserRuleCall_0_0 = (RuleCall)cGroup_0.eContents().get(0);
		private final Keyword cLeftParenthesisRightParenthesisKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final RuleCall cFunctionReferenceParserRuleCall_1_0 = (RuleCall)cGroup_1.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cArgsAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cArgsExpressionParserRuleCall_1_2_0 = (RuleCall)cArgsAssignment_1_2.eContents().get(0);
		private final Group cGroup_1_3 = (Group)cGroup_1.eContents().get(3);
		private final Keyword cCommaKeyword_1_3_0 = (Keyword)cGroup_1_3.eContents().get(0);
		private final Assignment cArgsAssignment_1_3_1 = (Assignment)cGroup_1_3.eContents().get(1);
		private final RuleCall cArgsExpressionParserRuleCall_1_3_1_0 = (RuleCall)cArgsAssignment_1_3_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_1_4 = (Keyword)cGroup_1.eContents().get(4);
		
		//FunctionCall:
		//	FunctionReference "()" | FunctionReference "(" args+=Expression ("," args+=Expression)* ")";
		public ParserRule getRule() { return rule; }

		//FunctionReference "()" | FunctionReference "(" args+=Expression ("," args+=Expression)* ")"
		public Alternatives getAlternatives() { return cAlternatives; }

		//FunctionReference "()"
		public Group getGroup_0() { return cGroup_0; }

		//FunctionReference
		public RuleCall getFunctionReferenceParserRuleCall_0_0() { return cFunctionReferenceParserRuleCall_0_0; }

		//"()"
		public Keyword getLeftParenthesisRightParenthesisKeyword_0_1() { return cLeftParenthesisRightParenthesisKeyword_0_1; }

		//FunctionReference "(" args+=Expression ("," args+=Expression)* ")"
		public Group getGroup_1() { return cGroup_1; }

		//FunctionReference
		public RuleCall getFunctionReferenceParserRuleCall_1_0() { return cFunctionReferenceParserRuleCall_1_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_1_1() { return cLeftParenthesisKeyword_1_1; }

		//args+=Expression
		public Assignment getArgsAssignment_1_2() { return cArgsAssignment_1_2; }

		//Expression
		public RuleCall getArgsExpressionParserRuleCall_1_2_0() { return cArgsExpressionParserRuleCall_1_2_0; }

		//("," args+=Expression)*
		public Group getGroup_1_3() { return cGroup_1_3; }

		//","
		public Keyword getCommaKeyword_1_3_0() { return cCommaKeyword_1_3_0; }

		//args+=Expression
		public Assignment getArgsAssignment_1_3_1() { return cArgsAssignment_1_3_1; }

		//Expression
		public RuleCall getArgsExpressionParserRuleCall_1_3_1_0() { return cArgsExpressionParserRuleCall_1_3_1_0; }

		//")"
		public Keyword getRightParenthesisKeyword_1_4() { return cRightParenthesisKeyword_1_4; }
	}

	public class VariableReferenceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "VariableReference");
		private final Assignment cVarIDAssignment = (Assignment)rule.eContents().get(1);
		private final CrossReference cVarIDVariableNameCrossReference_0 = (CrossReference)cVarIDAssignment.eContents().get(0);
		private final RuleCall cVarIDVariableNameIDTerminalRuleCall_0_1 = (RuleCall)cVarIDVariableNameCrossReference_0.eContents().get(1);
		
		/// *
		// * Variables
		// * / VariableReference:
		//	varID=[VariableName];
		public ParserRule getRule() { return rule; }

		//varID=[VariableName]
		public Assignment getVarIDAssignment() { return cVarIDAssignment; }

		//[VariableName]
		public CrossReference getVarIDVariableNameCrossReference_0() { return cVarIDVariableNameCrossReference_0; }

		//ID
		public RuleCall getVarIDVariableNameIDTerminalRuleCall_0_1() { return cVarIDVariableNameIDTerminalRuleCall_0_1; }
	}

	public class VariableNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "VariableName");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_0 = (RuleCall)cNameAssignment.eContents().get(0);
		
		//VariableName:
		//	name=ID;
		public ParserRule getRule() { return rule; }

		//name=ID
		public Assignment getNameAssignment() { return cNameAssignment; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_0() { return cNameIDTerminalRuleCall_0; }
	}

	public class NumberLiteralElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "NumberLiteral");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cSTRINGTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//NumberLiteral:
		//	INT | STRING;
		public ParserRule getRule() { return rule; }

		//INT | STRING
		public Alternatives getAlternatives() { return cAlternatives; }

		//INT
		public RuleCall getINTTerminalRuleCall_0() { return cINTTerminalRuleCall_0; }

		//STRING
		public RuleCall getSTRINGTerminalRuleCall_1() { return cSTRINGTerminalRuleCall_1; }
	}

	public class ExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Expression");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cVarAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cVarVariableReferenceParserRuleCall_0_0 = (RuleCall)cVarAssignment_0.eContents().get(0);
		private final RuleCall cNumberLiteralParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final Alternatives cAlternatives_2_0 = (Alternatives)cGroup_2.eContents().get(0);
		private final Keyword cExclamationMarkKeyword_2_0_0 = (Keyword)cAlternatives_2_0.eContents().get(0);
		private final Keyword cSizeofKeyword_2_0_1 = (Keyword)cAlternatives_2_0.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_2_1 = (Keyword)cGroup_2.eContents().get(1);
		private final Assignment cExpAssignment_2_2 = (Assignment)cGroup_2.eContents().get(2);
		private final RuleCall cExpExpressionParserRuleCall_2_2_0 = (RuleCall)cExpAssignment_2_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_2_3 = (Keyword)cGroup_2.eContents().get(3);
		private final Group cGroup_3 = (Group)cAlternatives.eContents().get(3);
		private final Alternatives cAlternatives_3_0 = (Alternatives)cGroup_3.eContents().get(0);
		private final Keyword cAllKeyword_3_0_0 = (Keyword)cAlternatives_3_0.eContents().get(0);
		private final Keyword cAnyKeyword_3_0_1 = (Keyword)cAlternatives_3_0.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Keyword cVarKeyword_3_2 = (Keyword)cGroup_3.eContents().get(2);
		private final Assignment cVarNameAssignment_3_3 = (Assignment)cGroup_3.eContents().get(3);
		private final RuleCall cVarNameVariableNameParserRuleCall_3_3_0 = (RuleCall)cVarNameAssignment_3_3.eContents().get(0);
		private final Keyword cHyphenMinusGreaterThanSignKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Assignment cExpAssignment_3_5 = (Assignment)cGroup_3.eContents().get(5);
		private final RuleCall cExpExpressionParserRuleCall_3_5_0 = (RuleCall)cExpAssignment_3_5.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3_6 = (Keyword)cGroup_3.eContents().get(6);
		private final Group cGroup_4 = (Group)cAlternatives.eContents().get(4);
		private final Alternatives cAlternatives_4_0 = (Alternatives)cGroup_4.eContents().get(0);
		private final Keyword cEqualsSignEqualsSignKeyword_4_0_0 = (Keyword)cAlternatives_4_0.eContents().get(0);
		private final Keyword cLessThanSignKeyword_4_0_1 = (Keyword)cAlternatives_4_0.eContents().get(1);
		private final Keyword cGreaterThanSignKeyword_4_0_2 = (Keyword)cAlternatives_4_0.eContents().get(2);
		private final Assignment cLeftAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cLeftExpressionParserRuleCall_4_1_0 = (RuleCall)cLeftAssignment_4_1.eContents().get(0);
		private final Assignment cRightAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cRightExpressionParserRuleCall_4_2_0 = (RuleCall)cRightAssignment_4_2.eContents().get(0);
		private final Assignment cActAssignment_5 = (Assignment)cAlternatives.eContents().get(5);
		private final RuleCall cActActionExpressionParserRuleCall_5_0 = (RuleCall)cActAssignment_5.eContents().get(0);
		
		/// *
		// * Expression
		// * / Expression:
		//	var=VariableReference | NumberLiteral | ("!" | "sizeof") "(" exp=Expression ")" | ("All" | "Any") "(" "var"
		//	varName=VariableName "->" exp=Expression ")" | ("==" | "<" | ">") left=Expression right=Expression |
		//	act=ActionExpression;
		public ParserRule getRule() { return rule; }

		//var=VariableReference | NumberLiteral | ("!" | "sizeof") "(" exp=Expression ")" | ("All" | "Any") "(" "var"
		//varName=VariableName "->" exp=Expression ")" | ("==" | "<" | ">") left=Expression right=Expression |
		//act=ActionExpression
		public Alternatives getAlternatives() { return cAlternatives; }

		//var=VariableReference
		public Assignment getVarAssignment_0() { return cVarAssignment_0; }

		//VariableReference
		public RuleCall getVarVariableReferenceParserRuleCall_0_0() { return cVarVariableReferenceParserRuleCall_0_0; }

		//NumberLiteral
		public RuleCall getNumberLiteralParserRuleCall_1() { return cNumberLiteralParserRuleCall_1; }

		//("!" | "sizeof") "(" exp=Expression ")"
		public Group getGroup_2() { return cGroup_2; }

		//"!" | "sizeof"
		public Alternatives getAlternatives_2_0() { return cAlternatives_2_0; }

		//"!"
		public Keyword getExclamationMarkKeyword_2_0_0() { return cExclamationMarkKeyword_2_0_0; }

		//"sizeof"
		public Keyword getSizeofKeyword_2_0_1() { return cSizeofKeyword_2_0_1; }

		//"("
		public Keyword getLeftParenthesisKeyword_2_1() { return cLeftParenthesisKeyword_2_1; }

		//exp=Expression
		public Assignment getExpAssignment_2_2() { return cExpAssignment_2_2; }

		//Expression
		public RuleCall getExpExpressionParserRuleCall_2_2_0() { return cExpExpressionParserRuleCall_2_2_0; }

		//")"
		public Keyword getRightParenthesisKeyword_2_3() { return cRightParenthesisKeyword_2_3; }

		//("All" | "Any") "(" "var" varName=VariableName "->" exp=Expression ")"
		public Group getGroup_3() { return cGroup_3; }

		//"All" | "Any"
		public Alternatives getAlternatives_3_0() { return cAlternatives_3_0; }

		//"All"
		public Keyword getAllKeyword_3_0_0() { return cAllKeyword_3_0_0; }

		//"Any"
		public Keyword getAnyKeyword_3_0_1() { return cAnyKeyword_3_0_1; }

		//"("
		public Keyword getLeftParenthesisKeyword_3_1() { return cLeftParenthesisKeyword_3_1; }

		//"var"
		public Keyword getVarKeyword_3_2() { return cVarKeyword_3_2; }

		//varName=VariableName
		public Assignment getVarNameAssignment_3_3() { return cVarNameAssignment_3_3; }

		//VariableName
		public RuleCall getVarNameVariableNameParserRuleCall_3_3_0() { return cVarNameVariableNameParserRuleCall_3_3_0; }

		//"->"
		public Keyword getHyphenMinusGreaterThanSignKeyword_3_4() { return cHyphenMinusGreaterThanSignKeyword_3_4; }

		//exp=Expression
		public Assignment getExpAssignment_3_5() { return cExpAssignment_3_5; }

		//Expression
		public RuleCall getExpExpressionParserRuleCall_3_5_0() { return cExpExpressionParserRuleCall_3_5_0; }

		//")"
		public Keyword getRightParenthesisKeyword_3_6() { return cRightParenthesisKeyword_3_6; }

		//("==" | "<" | ">") left=Expression right=Expression
		public Group getGroup_4() { return cGroup_4; }

		//"==" | "<" | ">"
		public Alternatives getAlternatives_4_0() { return cAlternatives_4_0; }

		//"=="
		public Keyword getEqualsSignEqualsSignKeyword_4_0_0() { return cEqualsSignEqualsSignKeyword_4_0_0; }

		//"<"
		public Keyword getLessThanSignKeyword_4_0_1() { return cLessThanSignKeyword_4_0_1; }

		//">"
		public Keyword getGreaterThanSignKeyword_4_0_2() { return cGreaterThanSignKeyword_4_0_2; }

		//left=Expression
		public Assignment getLeftAssignment_4_1() { return cLeftAssignment_4_1; }

		//Expression
		public RuleCall getLeftExpressionParserRuleCall_4_1_0() { return cLeftExpressionParserRuleCall_4_1_0; }

		//right=Expression
		public Assignment getRightAssignment_4_2() { return cRightAssignment_4_2; }

		//Expression
		public RuleCall getRightExpressionParserRuleCall_4_2_0() { return cRightExpressionParserRuleCall_4_2_0; }

		//act=ActionExpression
		public Assignment getActAssignment_5() { return cActAssignment_5; }

		//ActionExpression
		public RuleCall getActActionExpressionParserRuleCall_5_0() { return cActActionExpressionParserRuleCall_5_0; }
	}

	public class InstructionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Instruction");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cDefAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cDefDefinitionParserRuleCall_0_0 = (RuleCall)cDefAssignment_0.eContents().get(0);
		private final Assignment cFuncAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final RuleCall cFuncFunctionCallParserRuleCall_1_0 = (RuleCall)cFuncAssignment_1.eContents().get(0);
		private final Assignment cCondAssignment_2 = (Assignment)cAlternatives.eContents().get(2);
		private final RuleCall cCondConditionalParserRuleCall_2_0 = (RuleCall)cCondAssignment_2.eContents().get(0);
		private final Assignment cLoopAssignment_3 = (Assignment)cAlternatives.eContents().get(3);
		private final RuleCall cLoopLoopParserRuleCall_3_0 = (RuleCall)cLoopAssignment_3.eContents().get(0);
		private final Assignment cActAssignment_4 = (Assignment)cAlternatives.eContents().get(4);
		private final RuleCall cActActionInstructionParserRuleCall_4_0 = (RuleCall)cActAssignment_4.eContents().get(0);
		private final Assignment cAssAssignment_5 = (Assignment)cAlternatives.eContents().get(5);
		private final RuleCall cAssAssignationParserRuleCall_5_0 = (RuleCall)cAssAssignment_5.eContents().get(0);
		
		/// *
		// * Type of Instruction
		// * / Instruction:
		//	def=Definition | func=FunctionCall | cond=Conditional | loop=Loop | act=ActionInstruction | ass=Assignation;
		public ParserRule getRule() { return rule; }

		//def=Definition | func=FunctionCall | cond=Conditional | loop=Loop | act=ActionInstruction | ass=Assignation
		public Alternatives getAlternatives() { return cAlternatives; }

		//def=Definition
		public Assignment getDefAssignment_0() { return cDefAssignment_0; }

		//Definition
		public RuleCall getDefDefinitionParserRuleCall_0_0() { return cDefDefinitionParserRuleCall_0_0; }

		//func=FunctionCall
		public Assignment getFuncAssignment_1() { return cFuncAssignment_1; }

		//FunctionCall
		public RuleCall getFuncFunctionCallParserRuleCall_1_0() { return cFuncFunctionCallParserRuleCall_1_0; }

		//cond=Conditional
		public Assignment getCondAssignment_2() { return cCondAssignment_2; }

		//Conditional
		public RuleCall getCondConditionalParserRuleCall_2_0() { return cCondConditionalParserRuleCall_2_0; }

		//loop=Loop
		public Assignment getLoopAssignment_3() { return cLoopAssignment_3; }

		//Loop
		public RuleCall getLoopLoopParserRuleCall_3_0() { return cLoopLoopParserRuleCall_3_0; }

		//act=ActionInstruction
		public Assignment getActAssignment_4() { return cActAssignment_4; }

		//ActionInstruction
		public RuleCall getActActionInstructionParserRuleCall_4_0() { return cActActionInstructionParserRuleCall_4_0; }

		//ass=Assignation
		public Assignment getAssAssignment_5() { return cAssAssignment_5; }

		//Assignation
		public RuleCall getAssAssignationParserRuleCall_5_0() { return cAssAssignationParserRuleCall_5_0; }
	}

	public class DefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Definition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cVarKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cVarIDAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cVarIDVariableNameParserRuleCall_1_0 = (RuleCall)cVarIDAssignment_1.eContents().get(0);
		private final Keyword cEqualsSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cExpAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cExpExpressionParserRuleCall_3_0 = (RuleCall)cExpAssignment_3.eContents().get(0);
		
		//Definition:
		//	"var" varID=VariableName "=" exp=Expression;
		public ParserRule getRule() { return rule; }

		//"var" varID=VariableName "=" exp=Expression
		public Group getGroup() { return cGroup; }

		//"var"
		public Keyword getVarKeyword_0() { return cVarKeyword_0; }

		//varID=VariableName
		public Assignment getVarIDAssignment_1() { return cVarIDAssignment_1; }

		//VariableName
		public RuleCall getVarIDVariableNameParserRuleCall_1_0() { return cVarIDVariableNameParserRuleCall_1_0; }

		//"="
		public Keyword getEqualsSignKeyword_2() { return cEqualsSignKeyword_2; }

		//exp=Expression
		public Assignment getExpAssignment_3() { return cExpAssignment_3; }

		//Expression
		public RuleCall getExpExpressionParserRuleCall_3_0() { return cExpExpressionParserRuleCall_3_0; }
	}

	public class AssignationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Assignation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cVarAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cVarVariableReferenceParserRuleCall_0_0 = (RuleCall)cVarAssignment_0.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cExpAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cExpExpressionParserRuleCall_2_0 = (RuleCall)cExpAssignment_2.eContents().get(0);
		
		//Assignation:
		//	var=VariableReference "=" exp=Expression;
		public ParserRule getRule() { return rule; }

		//var=VariableReference "=" exp=Expression
		public Group getGroup() { return cGroup; }

		//var=VariableReference
		public Assignment getVarAssignment_0() { return cVarAssignment_0; }

		//VariableReference
		public RuleCall getVarVariableReferenceParserRuleCall_0_0() { return cVarVariableReferenceParserRuleCall_0_0; }

		//"="
		public Keyword getEqualsSignKeyword_1() { return cEqualsSignKeyword_1; }

		//exp=Expression
		public Assignment getExpAssignment_2() { return cExpAssignment_2; }

		//Expression
		public RuleCall getExpExpressionParserRuleCall_2_0() { return cExpExpressionParserRuleCall_2_0; }
	}

	public class ConditionalElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Conditional");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cIfKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cExpAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cExpExpressionParserRuleCall_1_0 = (RuleCall)cExpAssignment_1.eContents().get(0);
		private final Keyword cThenKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cInsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cInsInstructionParserRuleCall_3_0 = (RuleCall)cInsAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cElseKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cInsAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cInsInstructionParserRuleCall_4_1_0 = (RuleCall)cInsAssignment_4_1.eContents().get(0);
		private final Keyword cEndifKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Conditional:
		//	"if" exp=Expression "then" ins+=Instruction+ ("else" ins+=Instruction+)? "endif";
		public ParserRule getRule() { return rule; }

		//"if" exp=Expression "then" ins+=Instruction+ ("else" ins+=Instruction+)? "endif"
		public Group getGroup() { return cGroup; }

		//"if"
		public Keyword getIfKeyword_0() { return cIfKeyword_0; }

		//exp=Expression
		public Assignment getExpAssignment_1() { return cExpAssignment_1; }

		//Expression
		public RuleCall getExpExpressionParserRuleCall_1_0() { return cExpExpressionParserRuleCall_1_0; }

		//"then"
		public Keyword getThenKeyword_2() { return cThenKeyword_2; }

		//ins+=Instruction+
		public Assignment getInsAssignment_3() { return cInsAssignment_3; }

		//Instruction
		public RuleCall getInsInstructionParserRuleCall_3_0() { return cInsInstructionParserRuleCall_3_0; }

		//("else" ins+=Instruction+)?
		public Group getGroup_4() { return cGroup_4; }

		//"else"
		public Keyword getElseKeyword_4_0() { return cElseKeyword_4_0; }

		//ins+=Instruction+
		public Assignment getInsAssignment_4_1() { return cInsAssignment_4_1; }

		//Instruction
		public RuleCall getInsInstructionParserRuleCall_4_1_0() { return cInsInstructionParserRuleCall_4_1_0; }

		//"endif"
		public Keyword getEndifKeyword_5() { return cEndifKeyword_5; }
	}

	public class LoopElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Loop");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cWhileAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cWhileWhileParserRuleCall_0_0 = (RuleCall)cWhileAssignment_0.eContents().get(0);
		private final Assignment cForAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final RuleCall cForForeachParserRuleCall_1_0 = (RuleCall)cForAssignment_1.eContents().get(0);
		
		/// *
		// * Loop et Conditional
		// * / Loop:
		//	while=While | for=Foreach;
		public ParserRule getRule() { return rule; }

		//while=While | for=Foreach
		public Alternatives getAlternatives() { return cAlternatives; }

		//while=While
		public Assignment getWhileAssignment_0() { return cWhileAssignment_0; }

		//While
		public RuleCall getWhileWhileParserRuleCall_0_0() { return cWhileWhileParserRuleCall_0_0; }

		//for=Foreach
		public Assignment getForAssignment_1() { return cForAssignment_1; }

		//Foreach
		public RuleCall getForForeachParserRuleCall_1_0() { return cForForeachParserRuleCall_1_0; }
	}

	public class WhileElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "While");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cWhileKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cCondAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cCondExpressionParserRuleCall_2_0 = (RuleCall)cCondAssignment_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cDoKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cInsAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cInsInstructionParserRuleCall_5_0 = (RuleCall)cInsAssignment_5.eContents().get(0);
		private final Keyword cEndwhileKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//While:
		//	"while" "(" cond=Expression ")" "do" ins+=Instruction+ "endwhile";
		public ParserRule getRule() { return rule; }

		//"while" "(" cond=Expression ")" "do" ins+=Instruction+ "endwhile"
		public Group getGroup() { return cGroup; }

		//"while"
		public Keyword getWhileKeyword_0() { return cWhileKeyword_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }

		//cond=Expression
		public Assignment getCondAssignment_2() { return cCondAssignment_2; }

		//Expression
		public RuleCall getCondExpressionParserRuleCall_2_0() { return cCondExpressionParserRuleCall_2_0; }

		//")"
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }

		//"do"
		public Keyword getDoKeyword_4() { return cDoKeyword_4; }

		//ins+=Instruction+
		public Assignment getInsAssignment_5() { return cInsAssignment_5; }

		//Instruction
		public RuleCall getInsInstructionParserRuleCall_5_0() { return cInsInstructionParserRuleCall_5_0; }

		//"endwhile"
		public Keyword getEndwhileKeyword_6() { return cEndwhileKeyword_6; }
	}

	public class ForeachElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Foreach");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cForeachKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cVarAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cVarVariableNameParserRuleCall_2_0 = (RuleCall)cVarAssignment_2.eContents().get(0);
		private final Keyword cInKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cExpAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cExpExpressionParserRuleCall_4_0 = (RuleCall)cExpAssignment_4.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cDoKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cInsAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cInsInstructionParserRuleCall_7_0 = (RuleCall)cInsAssignment_7.eContents().get(0);
		private final Keyword cEndforKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Foreach:
		//	"foreach" "(" var=VariableName "in" exp=Expression ")" "do" ins+=Instruction+ "endfor";
		public ParserRule getRule() { return rule; }

		//"foreach" "(" var=VariableName "in" exp=Expression ")" "do" ins+=Instruction+ "endfor"
		public Group getGroup() { return cGroup; }

		//"foreach"
		public Keyword getForeachKeyword_0() { return cForeachKeyword_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }

		//var=VariableName
		public Assignment getVarAssignment_2() { return cVarAssignment_2; }

		//VariableName
		public RuleCall getVarVariableNameParserRuleCall_2_0() { return cVarVariableNameParserRuleCall_2_0; }

		//"in"
		public Keyword getInKeyword_3() { return cInKeyword_3; }

		//exp=Expression
		public Assignment getExpAssignment_4() { return cExpAssignment_4; }

		//Expression
		public RuleCall getExpExpressionParserRuleCall_4_0() { return cExpExpressionParserRuleCall_4_0; }

		//")"
		public Keyword getRightParenthesisKeyword_5() { return cRightParenthesisKeyword_5; }

		//"do"
		public Keyword getDoKeyword_6() { return cDoKeyword_6; }

		//ins+=Instruction+
		public Assignment getInsAssignment_7() { return cInsAssignment_7; }

		//Instruction
		public RuleCall getInsInstructionParserRuleCall_7_0() { return cInsInstructionParserRuleCall_7_0; }

		//"endfor"
		public Keyword getEndforKeyword_8() { return cEndforKeyword_8; }
	}

	public class ActionInstructionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ActionInstruction");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Keyword cOpenKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Assignment cUrlAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cUrlURLTerminalRuleCall_0_1_0 = (RuleCall)cUrlAssignment_0_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_0_2 = (Keyword)cGroup_0.eContents().get(2);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Alternatives cAlternatives_1_0 = (Alternatives)cGroup_1.eContents().get(0);
		private final Keyword cCheckKeyword_1_0_0 = (Keyword)cAlternatives_1_0.eContents().get(0);
		private final Keyword cClickKeyword_1_0_1 = (Keyword)cAlternatives_1_0.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cElementAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cElementExpressionParserRuleCall_1_2_0 = (RuleCall)cElementAssignment_1_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_1_3 = (Keyword)cGroup_1.eContents().get(3);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final Keyword cTypeKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cElementAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cElementExpressionParserRuleCall_2_1_0 = (RuleCall)cElementAssignment_2_1.eContents().get(0);
		private final Keyword cCommaKeyword_2_2 = (Keyword)cGroup_2.eContents().get(2);
		private final Assignment cValueAssignment_2_3 = (Assignment)cGroup_2.eContents().get(3);
		private final RuleCall cValueExpressionParserRuleCall_2_3_0 = (RuleCall)cValueAssignment_2_3.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_2_4 = (Keyword)cGroup_2.eContents().get(4);
		
		//ActionInstruction:
		//	"open(" url=URL ")" | ("check" | "click") "(" element=Expression ")" | "type(" element=Expression ","
		//	value=Expression ")";
		public ParserRule getRule() { return rule; }

		//"open(" url=URL ")" | ("check" | "click") "(" element=Expression ")" | "type(" element=Expression "," value=Expression
		//")"
		public Alternatives getAlternatives() { return cAlternatives; }

		//"open(" url=URL ")"
		public Group getGroup_0() { return cGroup_0; }

		//"open("
		public Keyword getOpenKeyword_0_0() { return cOpenKeyword_0_0; }

		//url=URL
		public Assignment getUrlAssignment_0_1() { return cUrlAssignment_0_1; }

		//URL
		public RuleCall getUrlURLTerminalRuleCall_0_1_0() { return cUrlURLTerminalRuleCall_0_1_0; }

		//")"
		public Keyword getRightParenthesisKeyword_0_2() { return cRightParenthesisKeyword_0_2; }

		//("check" | "click") "(" element=Expression ")"
		public Group getGroup_1() { return cGroup_1; }

		//"check" | "click"
		public Alternatives getAlternatives_1_0() { return cAlternatives_1_0; }

		//"check"
		public Keyword getCheckKeyword_1_0_0() { return cCheckKeyword_1_0_0; }

		//"click"
		public Keyword getClickKeyword_1_0_1() { return cClickKeyword_1_0_1; }

		//"("
		public Keyword getLeftParenthesisKeyword_1_1() { return cLeftParenthesisKeyword_1_1; }

		//element=Expression
		public Assignment getElementAssignment_1_2() { return cElementAssignment_1_2; }

		//Expression
		public RuleCall getElementExpressionParserRuleCall_1_2_0() { return cElementExpressionParserRuleCall_1_2_0; }

		//")"
		public Keyword getRightParenthesisKeyword_1_3() { return cRightParenthesisKeyword_1_3; }

		//"type(" element=Expression "," value=Expression ")"
		public Group getGroup_2() { return cGroup_2; }

		//"type("
		public Keyword getTypeKeyword_2_0() { return cTypeKeyword_2_0; }

		//element=Expression
		public Assignment getElementAssignment_2_1() { return cElementAssignment_2_1; }

		//Expression
		public RuleCall getElementExpressionParserRuleCall_2_1_0() { return cElementExpressionParserRuleCall_2_1_0; }

		//","
		public Keyword getCommaKeyword_2_2() { return cCommaKeyword_2_2; }

		//value=Expression
		public Assignment getValueAssignment_2_3() { return cValueAssignment_2_3; }

		//Expression
		public RuleCall getValueExpressionParserRuleCall_2_3_0() { return cValueExpressionParserRuleCall_2_3_0; }

		//")"
		public Keyword getRightParenthesisKeyword_2_4() { return cRightParenthesisKeyword_2_4; }
	}

	public class ActionExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ActionExpression");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final Keyword cVerifyKeyword_0_0 = (Keyword)cAlternatives_0.eContents().get(0);
		private final Keyword cSelectKeyword_0_1 = (Keyword)cAlternatives_0.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cElementAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cElementExpressionParserRuleCall_2_0 = (RuleCall)cElementAssignment_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//ActionExpression:
		//	("verify" | "select") "(" element=Expression ")";
		public ParserRule getRule() { return rule; }

		//("verify" | "select") "(" element=Expression ")"
		public Group getGroup() { return cGroup; }

		//"verify" | "select"
		public Alternatives getAlternatives_0() { return cAlternatives_0; }

		//"verify"
		public Keyword getVerifyKeyword_0_0() { return cVerifyKeyword_0_0; }

		//"select"
		public Keyword getSelectKeyword_0_1() { return cSelectKeyword_0_1; }

		//"("
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }

		//element=Expression
		public Assignment getElementAssignment_2() { return cElementAssignment_2; }

		//Expression
		public RuleCall getElementExpressionParserRuleCall_2_0() { return cElementExpressionParserRuleCall_2_0; }

		//")"
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }
	}
	
	
	private final ModelElements pModel;
	private final SubprocedureElements pSubprocedure;
	private final HeadElements pHead;
	private final FunctionReferenceElements pFunctionReference;
	private final FunctionNameElements pFunctionName;
	private final FunctionCallElements pFunctionCall;
	private final VariableReferenceElements pVariableReference;
	private final VariableNameElements pVariableName;
	private final NumberLiteralElements pNumberLiteral;
	private final ExpressionElements pExpression;
	private final InstructionElements pInstruction;
	private final DefinitionElements pDefinition;
	private final AssignationElements pAssignation;
	private final ConditionalElements pConditional;
	private final LoopElements pLoop;
	private final WhileElements pWhile;
	private final ForeachElements pForeach;
	private final ActionInstructionElements pActionInstruction;
	private final ActionExpressionElements pActionExpression;
	private final TerminalRule tURL;
	
	private final Grammar grammar;

	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public SlnDslGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pSubprocedure = new SubprocedureElements();
		this.pHead = new HeadElements();
		this.pFunctionReference = new FunctionReferenceElements();
		this.pFunctionName = new FunctionNameElements();
		this.pFunctionCall = new FunctionCallElements();
		this.pVariableReference = new VariableReferenceElements();
		this.pVariableName = new VariableNameElements();
		this.pNumberLiteral = new NumberLiteralElements();
		this.pExpression = new ExpressionElements();
		this.pInstruction = new InstructionElements();
		this.pDefinition = new DefinitionElements();
		this.pAssignation = new AssignationElements();
		this.pConditional = new ConditionalElements();
		this.pLoop = new LoopElements();
		this.pWhile = new WhileElements();
		this.pForeach = new ForeachElements();
		this.pActionInstruction = new ActionInstructionElements();
		this.pActionExpression = new ActionExpressionElements();
		this.tURL = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "URL");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("com.selenium.gram.xtext.SlnDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	/// *
	// * Le modele
	// * / Model:
	//	subs+=Subprocedure* "main" main+=Instruction+ "endmain";
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}

	//Subprocedure:
	//	"sub" head=Head body+=Instruction+ "endsub";
	public SubprocedureElements getSubprocedureAccess() {
		return pSubprocedure;
	}
	
	public ParserRule getSubprocedureRule() {
		return getSubprocedureAccess().getRule();
	}

	//Head:
	//	name=FunctionName "()" | name=FunctionName "(" "var" argsID+=VariableName ("," "var" argsID+=VariableName)* ")";
	public HeadElements getHeadAccess() {
		return pHead;
	}
	
	public ParserRule getHeadRule() {
		return getHeadAccess().getRule();
	}

	/// *
	// * Subprocedure
	// * / FunctionReference:
	//	functionName=[FunctionName];
	public FunctionReferenceElements getFunctionReferenceAccess() {
		return pFunctionReference;
	}
	
	public ParserRule getFunctionReferenceRule() {
		return getFunctionReferenceAccess().getRule();
	}

	//FunctionName:
	//	name=ID;
	public FunctionNameElements getFunctionNameAccess() {
		return pFunctionName;
	}
	
	public ParserRule getFunctionNameRule() {
		return getFunctionNameAccess().getRule();
	}

	//FunctionCall:
	//	FunctionReference "()" | FunctionReference "(" args+=Expression ("," args+=Expression)* ")";
	public FunctionCallElements getFunctionCallAccess() {
		return pFunctionCall;
	}
	
	public ParserRule getFunctionCallRule() {
		return getFunctionCallAccess().getRule();
	}

	/// *
	// * Variables
	// * / VariableReference:
	//	varID=[VariableName];
	public VariableReferenceElements getVariableReferenceAccess() {
		return pVariableReference;
	}
	
	public ParserRule getVariableReferenceRule() {
		return getVariableReferenceAccess().getRule();
	}

	//VariableName:
	//	name=ID;
	public VariableNameElements getVariableNameAccess() {
		return pVariableName;
	}
	
	public ParserRule getVariableNameRule() {
		return getVariableNameAccess().getRule();
	}

	//NumberLiteral:
	//	INT | STRING;
	public NumberLiteralElements getNumberLiteralAccess() {
		return pNumberLiteral;
	}
	
	public ParserRule getNumberLiteralRule() {
		return getNumberLiteralAccess().getRule();
	}

	/// *
	// * Expression
	// * / Expression:
	//	var=VariableReference | NumberLiteral | ("!" | "sizeof") "(" exp=Expression ")" | ("All" | "Any") "(" "var"
	//	varName=VariableName "->" exp=Expression ")" | ("==" | "<" | ">") left=Expression right=Expression |
	//	act=ActionExpression;
	public ExpressionElements getExpressionAccess() {
		return pExpression;
	}
	
	public ParserRule getExpressionRule() {
		return getExpressionAccess().getRule();
	}

	/// *
	// * Type of Instruction
	// * / Instruction:
	//	def=Definition | func=FunctionCall | cond=Conditional | loop=Loop | act=ActionInstruction | ass=Assignation;
	public InstructionElements getInstructionAccess() {
		return pInstruction;
	}
	
	public ParserRule getInstructionRule() {
		return getInstructionAccess().getRule();
	}

	//Definition:
	//	"var" varID=VariableName "=" exp=Expression;
	public DefinitionElements getDefinitionAccess() {
		return pDefinition;
	}
	
	public ParserRule getDefinitionRule() {
		return getDefinitionAccess().getRule();
	}

	//Assignation:
	//	var=VariableReference "=" exp=Expression;
	public AssignationElements getAssignationAccess() {
		return pAssignation;
	}
	
	public ParserRule getAssignationRule() {
		return getAssignationAccess().getRule();
	}

	//Conditional:
	//	"if" exp=Expression "then" ins+=Instruction+ ("else" ins+=Instruction+)? "endif";
	public ConditionalElements getConditionalAccess() {
		return pConditional;
	}
	
	public ParserRule getConditionalRule() {
		return getConditionalAccess().getRule();
	}

	/// *
	// * Loop et Conditional
	// * / Loop:
	//	while=While | for=Foreach;
	public LoopElements getLoopAccess() {
		return pLoop;
	}
	
	public ParserRule getLoopRule() {
		return getLoopAccess().getRule();
	}

	//While:
	//	"while" "(" cond=Expression ")" "do" ins+=Instruction+ "endwhile";
	public WhileElements getWhileAccess() {
		return pWhile;
	}
	
	public ParserRule getWhileRule() {
		return getWhileAccess().getRule();
	}

	//Foreach:
	//	"foreach" "(" var=VariableName "in" exp=Expression ")" "do" ins+=Instruction+ "endfor";
	public ForeachElements getForeachAccess() {
		return pForeach;
	}
	
	public ParserRule getForeachRule() {
		return getForeachAccess().getRule();
	}

	//ActionInstruction:
	//	"open(" url=URL ")" | ("check" | "click") "(" element=Expression ")" | "type(" element=Expression ","
	//	value=Expression ")";
	public ActionInstructionElements getActionInstructionAccess() {
		return pActionInstruction;
	}
	
	public ParserRule getActionInstructionRule() {
		return getActionInstructionAccess().getRule();
	}

	//ActionExpression:
	//	("verify" | "select") "(" element=Expression ")";
	public ActionExpressionElements getActionExpressionAccess() {
		return pActionExpression;
	}
	
	public ParserRule getActionExpressionRule() {
		return getActionExpressionAccess().getRule();
	}

	/// *
	// * URL
	// * / terminal URL:
	//	"a".."z"+ // Protocol
	//	"://" ("0".."9"+ "." "0".."9"+ "." "0".."9"+ "." "0".."9"+ // Hostname
	//	| ("a".."z" | "A".."Z") ("a".."z" | "A".."Z" | "0".."9" | "$" | "-" | "_" | "\\" ("0".."9" | "a".."f" | "A".."F")
	//	("0".."9" | "a".."f" | "A".."F") | "%" "0".."9" "0".."9")* ("." ("a".."z" | "A".."Z") ("a".."z" | "A".."Z" | "0".."9"
	//	| "$" | "-" | "_" | "\\" ("0".."9" | "a".."f" | "A".."F") ("0".."9" | "a".."f" | "A".."F") | "%" "0".."9"
	//	"0".."9")*)*) (":" "0".."9"+)? // Portnumber
	//	("/" ("a".."z" | "A".."Z" | "0".."9" | "$" | "-" | "_" | "~" | "+" | "." | "\\" ("0".."9" | "a".."f" | "A".."F")
	//	("0".."9" | "a".."f" | "A".."F") | "%" "0".."9" "0".."9")*)* // Path
	//	("?" ("a".."z" | "A".."Z" | "0".."9" | "$" | "-" | "_" | "=" | "&" | ";" | "\\" ("0".."9" | "a".."f" | "A".."F")
	//	("0".."9" | "a".."f" | "A".."F") | "%" "0".."9" "0".."9")+ ("+" ("a".."z" | "A".."Z" | "0".."9" | "$" | "-" | "_" |
	//	"=" | "&" | ";" | "\\" ("0".."9" | "a".."f" | "A".."F") ("0".."9" | "a".."f" | "A".."F") | "%" "0".."9"
	//	"0".."9")+)*)?;
	public TerminalRule getURLRule() {
		return tURL;
	} 

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" . / * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\""))* "\"" | "\'" ("\\" .
	//	/ * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
