/*
 * generated by Xtext
 */
package com.selenium.gram.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SlnDslUiModule extends com.selenium.gram.xtext.ui.AbstractSlnDslUiModule {
	public SlnDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
