/*
 * generated by Xtext
 */
package com.selenium.gram.xtext.ui.contentassist

import com.selenium.gram.xtext.ui.contentassist.AbstractSlnDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class SlnDslProposalProvider extends AbstractSlnDslProposalProvider {
}
