/*
 * generated by Xtext
 */
package com.selenium.gram.xtext.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractSlnDslValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(com.selenium.gram.xtext.slnDsl.SlnDslPackage.eINSTANCE);
		return result;
	}
}
