/*
* generated by Xtext
*/
package com.selenium.gram.xtext;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SlnDslStandaloneSetup extends SlnDslStandaloneSetupGenerated{

	public static void doSetup() {
		new SlnDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

